### ISSUE TITLE
SSL Error when starting wallet

### ISSUE THREAD

**Issue by FinalDayz** [duino-coin/duino-coin#1001]
When starting the Wallet, either using the .py, or .exe, it will give an SSL exception as soon if you try to login or register:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "Wallet.py", line 283, in _login_btn_clicked
  File "websocket\_core.py", line 597, in create_connection
  File "websocket\_core.py", line 249, in connect
  File "websocket\_http.py", line 121, in connect
  File "websocket\_http.py", line 253, in _ssl_socket
  File "websocket\_http.py", line 231, in _wrap_sni_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)
```

I got this error using Windows 10 and Ubuntu 20. Another Discord user tried the same with Ubuntu 21, but got the same error. This is with the newest release/code.

**To Reproduce**
Download newest release.
execute the wallet, or CLI_Wallet.
Using the CLI_Wallet, I am getting the error after starting, and using the UI Wallet I get the error after trying to login or register

**Expected behavior**
Logging in successfull

**System (please complete the following information):**
 - OS: Windows 10, Ubuntu 20 and 21
 - Software: CLI_Wallet and normal Wallet
 - Version: 2.7.2

**Comment by revoxhere** [comment]
gui wallet is no longer supported, use the webwallet

**Comment by FinalDayz** [comment]
Ahh, okay. Thanks for the quick response.
Does it include all the functionality, like wrapping to wDUCO with your key?
