### ISSUE TITLE
orangepi3 can‘t start PC_Miner.py

### ISSUE THREAD

**Issue by hahahaha-lang** [duino-coin/duino-coin#1017]
root@orangepi3:~/duino-coin# python3 PC_Miner.py
Traceback (most recent call last):
  File "PC_Miner.py", line 849, in <module>
    Miner.preload()
  File "PC_Miner.py", line 484, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by revoxhere** [comment]
Hello, try removing the Translations.json file and restarting the miner

**Comment by hahahaha-lang** [comment]
> Hello, try removing the Translations.json file and restarting the miner

How to do it,I not found the file

**Comment by hahahaha-lang** [comment]
> Hello, try removing the Translations.json file and restarting the miner

How to do it,I not found the file

**Comment by revoxhere** [comment]
It should be inside the `Duino Coin PC Miner 2.73` folder

**Comment by revoxhere** [comment]
Closing due to inactivity/solve in the latest versions
