### ISSUE TITLE
unable to start miner

### ISSUE THREAD

**Issue by mykroft** [duino-coin/duino-coin#1178]
rasp pi 4
get the following error when starting miner
`pi@RackPi1:~/duino-coin $ sudo python3 PC_Miner.py
Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner.py", line 845, in <module>
    Miner.greeting()
  File "/home/pi/duino-coin/PC_Miner.py", line 407, in greeting
    print("\n" + Style.DIM + Fore.YELLOW + Settings.BLOCK + Fore.YELLOW
  File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
  File "/usr/lib/python3.9/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2016' in position 11: character maps to <undefined>
`

**Comment by BastelPichi** [comment]
Hello,
Launching the Miner with sudo is not good practice - just leave it. For your problem, you need to have a codec like utf8. You can change that in raspi-config, under Localisation options.
