### ISSUE TITLE
jakiś błąd z pythonem

### ISSUE THREAD

**Issue by 8u83r70** [duino-coin/duino-coin#1191]
odpalam avr minera, próbuję kopać i po chwili wyskakuje taki błąd:

Exception in callback _ProactorBaseWritePipeTransport._loop_writing(<_OverlappedF...ed result=514>)
handle: <Handle _ProactorBaseWritePipeTransport._loop_writing(<_OverlappedF...ed result=514>)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 375, in _loop_writing
AssertionError

**Comment by 8u83r70** [comment]
jeszcze sam błąd to mi się zdaje, że to to jest 


Problem z płytką AVR! Ponowna próba za 10s (no response from the board: list index out of range, please check the connection, port setting or reset the AVR)
