### ISSUE TITLE
esptool.FatalError.Time out waiting for packet header

### ISSUE THREAD

**Issue by SemiTok2** [duino-coin/duino-coin#1215]
Arduino: 1.8.19 (Windows 8.1), Board: "NodeMCU 0.9 (ESP-12 Module), 160 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

ICACHE : 32768           - flash instruction cache 

IROM   : 401240          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 28968   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 

DATA   : 1504  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 2252  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 26248 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 433964 bytes (41%) of program storage space. Maximum is 1044464 bytes.

Global variables use 30004 bytes (36%) of dynamic memory, leaving 51916 bytes for local variables. Maximum is 81920 bytes.

esptool.py v3.0

Serial port COM3

Connecting....

Chip is ESP8266EX

Features: WiFi

Crystal is 26MHz

MAC: 34:ab:95:24:87:c0

Uploading stub...

Running stub...

Stub running...

Configuring flash size...

Warning: Could not auto-detect Flash size (FlashID=0x10064020, SizeID=0x1006), defaulting to 4MB

Compressed 438112 bytes to 320022...

Traceback (most recent call last):

  File "C:\Users\SemiTokz23\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1/tools/upload.py", line 66, in <module>

    esptool.main(cmdline)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 3604, in main

    operation_func(esp, args)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 2974, in write_flash

    blocks = esp.flash_defl_begin(uncsize, len(image), address)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 113, in inner

    return func(*args, **kwargs)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 752, in flash_defl_begin

    self.check_command("enter compressed flash mode", self.ESP_FLASH_DEFL_BEGIN, params, timeout=timeout)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 413, in check_command

    val, data = self.command(op, data, chk, timeout=timeout)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 386, in command

    p = self.read()

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 331, in read

    return next(self._slip_reader)

  File "C:/Users/SemiTokz23/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 2636, in slip_reader

    raise FatalError("Timed out waiting for packet %s" % waiting_for)

esptool.FatalError: Timed out waiting for packet header

esptool.FatalError: Timed out waiting for packet header

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by radimkarnis** [comment]
Hello @SemiTok2,
this esptool error is usually a result of a bad HW or connection. There are multiple things to check (such as a bad USB cable, ...).

See this [troubleshooting guide](https://docs.espressif.com/projects/esptool/en/latest/esp8266/troubleshooting.html) for more info!

**Comment by LDarki** [comment]
Hi, are you still having this problem?
If not tell me for close this issue

**Comment by LDarki** [comment]
No response.
I`ll close this issue
