### ISSUE TITLE
Updated to 3.0.0 and can't start the miner anymore

### ISSUE THREAD

**Issue by laroma** [duino-coin/duino-coin#1324]
After update I attempted to start the miner with `python3 PC_Miner.py` , but to no avail. Using rpi 3

```
Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner.py", line 982, in <module>
    Miner.preload()
  File "/home/pi/duino-coin/PC_Miner.py", line 542, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by LDarki** [comment]
Hi, can you send me your lang file ?

Edit:
Try deleting the config folder

**Comment by laroma** [comment]
> Hi, can you send me your lang file ?
> 
> Edit: Try deleting the config folder

Where those are located?

**Comment by LDarki** [comment]
In the same folder of the miner.
the folder name is Duino-Coin PC Miner 3.0

For example (on windows):
![image](https://user-images.githubusercontent.com/51938450/151699016-39c717d7-3ac5-4750-8f9a-27baa84e9710.png)

**Comment by laroma** [comment]
That did the trick. Thank you!
