### ISSUE TITLE
Duino mining raspberry Pi zero 

### ISSUE THREAD

**Issue by Amalax** [duino-coin/duino-coin#1411]
I have an error,when i run the pcminer. It show that pc miner is uptodate and showing thease error, please anyone help me do solve this

Downloading fasthash accelerations module
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0xb56f9b50>, 'Connection to server.duinocoin.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /fasthash/libducohashPiZero.so (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xb56f9b50>, 'Connection to server.duinocoin.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PC_Miner.py", line 1226, in <module>
    Fasthash.load()
  File "PC_Miner.py", line 1187, in load
    r = requests.get(url, timeout=10)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /fasthash/libducohashPiZero.so (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xb56f9b50>, 'Connection to server.duinocoin.com timed out. (connect timeout=10)'))

**Comment by LDarki** [comment]
Hi, are you still facing this issue ?

**Comment by LDarki** [comment]
No Response.
I'll close this issue.
