### ISSUE TITLE
Can't Start mining on windows or kali linux because connection refused

### ISSUE THREAD

**Issue by TomerGamerTV** [duino-coin/duino-coin#1593]
**Describe the bug**
After inputting my username it just throws a connection refused error

**To Reproduce**
1. Start the pc miner.py / .exe
2. Input username
3. Get error jumpscare

**Expected behavior**
Start mining of course

**Screenshots/photos**
```File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f38e7a28280>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomer/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/tomer/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /users/TomerGamerTV (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f38e7a28280>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomer/duino-coin-3.33/PC_Miner.py", line 1299, in <module>
    user_settings = Miner.load_cfg()
  File "/home/tomer/duino-coin-3.33/PC_Miner.py", line 875, in load_cfg
    r = requests.get(f"https://server.duinocoin.com/users/{username}",
  File "/home/tomer/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/tomer/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tomer/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tomer/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/tomer/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /users/TomerGamerTV (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f38e7a28280>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
(Similar thing on windows too i just tried running it in wsl)
**System (please complete the following information):**
 - OS: Windows 10 Pro / Kali linux WSL
 - Software: PC Miner
 - Version: 3.33

**Additional context**
I install this miner on my mac m1 yesterday and it works just fine. its connected to the same internet as my pc and idk how its still working because then i try the webminer it gives me some ssl error

**Comment by revoxhere** [comment]
Are you able to visit https://server.duinocoin.com in your browser?

**Comment by TomerGamerTV** [comment]
> Are you able to visit https://server.duinocoin.com in your browser?

Yes.

**Comment by TomerGamerTV** [comment]
Nvm I was able to fix it my stupid antivirus was blocking the ip the miner was trying to connect to.
