### ISSUE TITLE
PC_Miner.py (3.5) and Translations.json error

### ISSUE THREAD

**Issue by paranoid64** [duino-coin/duino-coin#1653]
**Describe:**
Translations.json is not valid if the  PC_Miner_3.5.py run at the first time.

This is the error:
pi@mypi:~/duino-coin $ python3 PC_Miner.py 
Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner.py", line 1307, in <module>
    Miner.preload()
  File "/home/pi/duino-coin/PC_Miner.py", line 815, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.9/json/init.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Solution**:

1.:

edit /duino-coin/Duino-Coin PC Miner 3.5/Translations.json

Find line 1889:
`        "donation_level": "Cấp độ ủng hộ nhà phát triển: ",,`

replace: 
`        "donation_level": "Cấp độ ủng hộ nhà phát triển: ",`

2.:

Find line 1981 - 1982:

```
        "motd": "Hôm nay, server cho bạn câu nói: ",

}
```

replace to:

```
        "motd": "Hôm nay, server cho bạn câu nói: "
    }
}
```

That's all :-)

**Comment by MinatoIsuki** [comment]
Oh boy :) Wonder why my translations refuse to run on PC Miner :)
Let me repair this then I will make another PR :)
