### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Data-Gremlin** [duino-coin/duino-coin#1657]
A new version is available, you want to update miner (Y/n) ? y
10:41:15  sys0  The miner is outdated. Updating....
10:41:15  sys0  Config saved! Launching the miner
10:41:15  sys0  Saving update to: /home/pi/duino-coin/PC_Miner_3.5.py
107% [###########################################################] 0.03 MB  3176.0 KB/s10:41:16  sys0  Download complete
Traceback (most recent call last):
  File "/home/pi/duino-coin/./PC_Miner_3.5.py", line 1307, in <module>
    Miner.preload()
  File "/home/pi/duino-coin/./PC_Miner_3.5.py", line 815, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1889 column 60 (char 124924)

**Comment by Data-Gremlin** [comment]
How is this complete ? I've had no feedback.

**Comment by Data-Gremlin** [comment]
@Tech1k

**Comment by tomasthedev** [comment]
Try download manualy

**Comment by Data-Gremlin** [comment]
tryed that now geting 

Traceback (most recent call last):
  File "/home/pi/duino-coin/PC_Miner_3.5.py", line 1307, in <module>
    Miner.preload()
  File "/home/pi/duino-coin/PC_Miner_3.5.py", line 815, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1889 column 60 (char 124924)


Can i just uninstall this and all parts then re install ? if so how ?
