### ISSUE TITLE
PC-miner v4.0, syntax error

### ISSUE THREAD

**Issue by PSLLSP** [duino-coin/duino-coin#1732]
Git repository updated to commit 03c3e13be1921794b18b1e118d94587939cb0126

I cannot start miner; it is RPI zero mini computer:

```
$ python3 --version
Python 3.7.3

$ cat miner.sh 
#!/bin/sh

[ -f bin/activate ] && . bin/activate

python3 PC_Miner.py "$@"

$ sh miner.sh 
Traceback (most recent call last):
  File "PC_Miner.py", line 1364, in <module>
    Miner.preload()
  File "PC_Miner.py", line 858, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1751 column 9 (char 115213)
```
---

Issue is in the file `Translations.json`, it is not valid JSON file:
```
$ jq . Duino-Coin\ PC\ Miner\ 4.0/Translations.json 
parse error: Expected separator between values at line 1751, column 24
```

**Comment by revoxhere** [comment]
Please remove the language file and try again in a few minutes. There was a typo in one of user contrubitions but has been fixed by now

**Comment by PSLLSP** [comment]
Yes, the issue was fixed; one comma was missing in the file that triggered this issue...
```
$ curl -s "https://raw.githubusercontent.com/revoxhere/duino-coin/master/Resources/PC_Miner_langs.json" | jq 'length'
22
```

**Comment by PSLLSP** [comment]
When I see the translations, I recommend to change this 
```
    "new_version": "A new version is available, you want to update miner [Y/n] ? ",
```

to 

```
    "new_version": "A new version is available. Do you want to update the miner [Y/n] ? ",
```

**Comment by revoxhere** [comment]
Updated.
