### ISSUE TITLE
AVR miner 4.0, accept not defined

### ISSUE THREAD

**Issue by PSLLSP** [duino-coin/duino-coin#1733]
AVR miner v4.0 running on some ARM computer, AVR miner is RPI-PCIO.

**It is REPEATABLE!!**

I see error `NameError: name 'accept' is not defined`:
```
...
19:50:21  avr0  ⛏ Accepted 89/89 (100%) ∙ 02.2s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:21  sys0  Periodic mining report: 
                ‖ During the last 60 seconds
                ‖ You've mined 46 shares (0.8 shares/s)
                ‖ Blocks found: 0
                ‖ With the hashrate of 21 kH/s
                ‖ In this time period, you've solved 1260733 hashes
                ‖ Total miner uptime: 2.0 minutes
19:50:22  avr0  ⛏ Accepted 90/90 (100%) ∙ 01.3s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:23  avr0  ⛏ Accepted 91/91 (100%) ∙ 00.8s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:24  avr0  ⛏ Accepted 92/92 (100%) ∙ 00.6s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:24  avr0  ⛏ Accepted 93/93 (100%) ∙ 00.3s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:26  avr0  ⛏ Accepted 94/94 (100%) ∙ 02.1s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:28  avr0  ⛏ Accepted 95/95 (100%) ∙ 02.3s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 14ms
19:50:30  avr0  ⛏ Accepted 96/96 (100%) ∙ 01.7s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 14ms
19:50:32  avr0  ⛏ Accepted 97/97 (100%) ∙ 01.7s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:34  avr0  ⛏ Accepted 98/98 (100%) ∙ 01.8s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
19:50:36  avr0  ⛏ Accepted 99/99 (100%) ∙ 02.3s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
Exception in thread Thread-2 (mine_avr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psl/duino-coin/AVR_Miner.py", line 1242, in mine_avr
    f"{get_string('surpassed')} {accept.value} {get_string('surpassed_shares')}",
                                 ^^^^^^
NameError: name 'accept' is not defined
19:50:38  avr0  ⛏ Accepted 100/100 (100%) ∙ 02.0s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
```

This is the miner:
```
$ sh miner-AVR.sh 

 ‖ Official Duino-Coin © AVR Miner 4.0 2019-2024
 ‖ https://github.com/revoxhere/duino-coin
 ‖ AVR board(s) on port(s): /dev/ttyACM0
 ‖ Developer donation level: 0
 ‖ Algorithm: DUCO-S1A ⚙ AVR diff
 ‖ Rig identifier: PICO
 ‖ Config file: Duino-Coin AVR Miner 4.0/Settings.cfg
 ‖ Have a cozy evening, miner!

21:17:20  net0  Searching for the fastest node to connect to
21:17:21  net0  Retrieved mining node: europe-node-2
21:17:23  net0  Connected to master Duino-Coin server (v4.0)
21:17:23  net0  Server message of the day: Welcome to europe node hosted by revox (inst. 2) | NEW: Exchange various cryptocoins fast on fluffyswap.com
21:17:23  sys0  AVR mining thread is starting using DUCO-S1A algorithm (/dev/ttyACM0)
21:17:23  sys0  Hashrate test ended with 20 kH/s, assigned starting difficulty: DUE
21:17:25  avr0  ⛏ Accepted 1/1 (100%) ∙ 01.4s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
21:17:26  avr0  ⛏ Accepted 2/2 (100%) ∙ 01.3s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
21:17:28  avr0  ⛏ Accepted 3/3 (100%) ∙ 01.8s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
21:17:29  avr0  ⛏ Accepted 4/4 (100%) ∙ 00.9s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
21:17:29  avr0  ⛏ Accepted 5/5 (100%) ∙ 00.5s ∙ 21 kH/s (21 kH/s total) ⚙ diff. 512 ∙ ping 15ms
...
```

**Comment by revoxhere** [comment]
Please re-download the code. This has been fixed about an hour ago :P

**Comment by PSLLSP** [comment]
> Please re-download the code. This has been fixed about an hour ago :P

I was using `git checkout 4.0`. New release, like 4.1, should be released soon...

**Comment by jon-moreira** [comment]
I Have the same issue with version 4,0

❯ ./AVR_Miner.py
21:42:50.930958 DEBUG: Config file loaded

```
 ‖ Official Duino-Coin © AVR Miner 4.0 2019-2024
 ‖ https://github.com/revoxhere/duino-coin
 ‖ AVR board(s) on port(s): /dev/cu.usbmodem141401
 ‖ Developer donation level: 0
 ‖ Algorithm: DUCO-S1A ⚙ AVR diff
 ‖ Rig identifier: ArduinoUNO
 ‖ Config file: Duino-Coin AVR Miner 4.0/Settings.cfg
[....]
22:07:52  avr141401  ⛏ Accepted 99/99 (100%) ∙ 00.1s ∙ 340 H/s (340 H/s total) ⚙ diff. 8 ∙ ping 56ms
Exception in thread Thread-2 (mine_avr):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pouic/Desktop/arduino/duino-coin-4.0/AVR_Miner.py", line 1242, in mine_avr
    f"{get_string('surpassed')} {accept.value} {get_string('surpassed_shares')}",
                                 ^^^^^^
NameError: name 'accept' is not defined
22:07:54  avr141401  ⛏ Accepted 100/100 (100%) ∙ 01.9s ∙ 340 H/s (340 H/s total) ⚙ diff. 8 ∙ ping 55ms
```
