### ISSUE TITLE
Exception in AVR miner

### ISSUE THREAD

**Issue by dra5** [duino-coin/duino-coin#1743]
After 4.0 update, exception, running always stops before the 100th share:

10:46:38  avr0  ⛏ Accepted 99/99 (100%) ∙ 01.2s ∙ 260 H/s (260 H/s total) ⚙ diff. 8 ∙ ping 45ms
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rock/nano/AVR_Miner.py", line 1242, in mine_avr
    f"{get_string('surpassed')} {accept.value} {get_string('surpassed_shares')}",
NameError: name 'accept' is not defined
10:46:40  avr0  ⛏ Accepted 100/100 (100%) ∙ 01.9s ∙ 260 H/s (260 H/s total) ⚙ diff. 8 ∙ ping 45ms

![avr-exception-before-100-shares](https://github.com/revoxhere/duino-coin/assets/7498165/8e02c579-dbbe-4ba9-80d7-d6f726502778)

**Comment by revoxhere** [comment]
Redownload the release.
