### ISSUE TITLE
Can't login if passwords contains a "%" character

### ISSUE THREAD

**Issue by endre90** [duino-coin/duino-coin#368]
Hey guys,

appreciate the work that you are doing, keep it up! 
I can't login if my passwords contains a "%" character, here is the log(ish):

File "/usr/lib/python3.6/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'xxxxx%xxxx' at position xx

Best Regards,
Endre

**Comment by endre90** [comment]
Sorry, should have provided the whole trace:

Traceback (most recent call last):
  File "./CLI_Wallet.py", line 355, in <module>
    "password": password}
  File "/usr/lib/python3.6/configparser.py", line 972, in __setitem__
    self.read_dict({key: value})
  File "/usr/lib/python3.6/configparser.py", line 754, in read_dict
    self.set(section, key, value)
  File "/usr/lib/python3.6/configparser.py", line 1193, in set
    super().set(section, option, value)
  File "/usr/lib/python3.6/configparser.py", line 894, in set
    value)
File "/usr/lib/python3.6/configparser.py", line 402, in before_set
"position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'xxxxx%xxxx' at position xx

Best,
Endre

**Comment by revoxhere** [comment]
I haven't thought someone would use these characters, I'll try doing something about it

**Comment by endre90** [comment]
Cool, thanks. I have another one :)

The setup let's me register with a long password, but when I try to login with it later, it is too long (probably):

Traceback (most recent call last):
  File "CLI_Wallet.py", line 365, in <module>
IndexError: list index out of range
[10385] Failed to execute script CLI_Wallet

Best,
Endre

**Comment by ivbeck** [comment]
Probably it is fixable by Regex-escaping special characters

**Comment by galaksian** [comment]
Hello guys,

Same issue for me I have set a password with a % and 64 chars long...
I can log with the GUI but not with the cli.
More than that I am not able to change my password...

What are the acceptable passwords ? How many chars ? Which chars ?

BR,
Galaksian
