### ISSUE TITLE
Cannot Mine Using AVR Miner

### ISSUE THREAD

**Issue by unixrobot0** [duino-coin/duino-coin#591]
Hey, When I try to mine using AVR Miner, I'm getting this nonsense:

`23:46:17  net0  Connected to master Duino-Coin server (v2.4)
23:46:17  usb0  AVR on port /dev/ttyACM0 is connected
23:46:17  sys0  AVR mining thread is starting using DUCO-S1A algorithm (/dev/ttyACM0)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "AVR_Miner.py", line 1029, in AVRMine
  File "colorama/ansitowin32.py", line 41, in write
  File "colorama/ansitowin32.py", line 164, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 53: ordinal not in range(128)
23:46:59  net0  Error connecting to the server. Retrying in 10s (local variable 'serverVersion' referenced before assignment)
23:47:15  net0  Connected to master Duino-Coin server (v2.4)
23:47:15  usb0  AVR on port /dev/ttyUSB0 is connected
23:47:15  sys0  AVR mining thread is starting using DUCO-S1A algorithm (/dev/ttyUSB0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "AVR_Miner.py", line 1029, in AVRMine
  File "colorama/ansitowin32.py", line 41, in write
  File "colorama/ansitowin32.py", line 164, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 53: ordinal not in range(128)`

How do I fix it?

**Comment by revoxhere** [comment]
Are you using the latest python version?
