### ISSUE TITLE
Cli wallet error when importing the private tron ​​key

### ISSUE THREAD

**Issue by epicmario7133** [duino-coin/duino-coin#656]
**Describe the bug**
once you set the private key and use the same password as duino from an error

**To Reproduce**
1. Use wrapperconf
2. Import key
3. use same password as duino
4. re open the cli wallet
5. See error

**Expected behavior**

**Screenshots/photos**
![Screenshot (518)](https://user-images.githubusercontent.com/56398081/125164166-2c9e2000-e191-11eb-97a5-bf7d5cf39554.png)

**System (please complete the following information):**
 - OS: Raspbien and same problem on Windows 10
 - Software Cli wallet
 - Version v2.52

**Additional context**
full error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/hmac.py", line 67, in verify
    ctx.verify(signature)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CLI_Wallet.py", line 456, in <module>
    config["wallet"]["password"]))[2:66]
  File "CLI_Wallet.py", line 215, in password_decrypt
    return Fernet(key).decrypt(token)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken

**Comment by ygboucherk** [comment]
Thanks for reporting. I'm currently investigating !

**Comment by ygboucherk** [comment]
Hmm basically new versions store a base64 representation of password when older ones used plain text.
So password was encrypted using base64 but it tried decrypting using plain text !
https://github.com/revoxhere/duino-coin/commit/b6cbba30c97796e378de54d1d42f34dd3b4f56d5

**Comment by ygboucherk** [comment]
Tell me if it worked !

**Comment by epicmario7133** [comment]
after updating the file i got a new error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/hmac.py", line 67, in verify
    ctx.verify(signature)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CLI_Wallet.py", line 456, in <module>
    config["wallet"]["password"]))[2:66]
  File "CLI_Wallet.py", line 215, in password_decrypt
    return Fernet(key).decrypt(token)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken

**Comment by ghost** [comment]
> Tell me if it worked !

looks like still having isssue in config even boolen true but cant get cofigured
