### ISSUE TITLE
Miner wont run on Windows Server 2012.

### ISSUE THREAD

**Issue by WolfRamiO74** [duino-coin/duino-coin#668]
`
C:\-Duino-Coin>pc_miner
Active code page: 65001

Traceback (most recent call last):
  File "PC_Miner.py", line 1453, in <module>
  File "PC_Miner.py", line 298, in Greeting
  File "colorama\ansitowin32.py", line 41, in write
  File "colorama\ansitowin32.py", line 162, in write
  File "colorama\ansitowin32.py", line 187, in write_and_convert
  File "colorama\ansitowin32.py", line 196, in write_plain_text
PermissionError: [WinError 31] A device attached to the system is not functionin
g

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PC_Miner.py", line 1456, in <module>
  File "PC_Miner.py", line 1262, in pretty_print
  File "colorama\ansitowin32.py", line 41, in write
  File "colorama\ansitowin32.py", line 162, in write
  File "colorama\ansitowin32.py", line 187, in write_and_convert
  File "colorama\ansitowin32.py", line 196, in write_plain_text
PermissionError: [WinError 31] A device attached to the system is not functionin
g
[1204] Failed to execute script PC_Miner
Traceback (most recent call last):
  File "<string>", line 1, in <module>
PermissionError: [WinError 31] A device attached to the system is not functionin
g
Exception ignored in: <colorama.ansitowin32.StreamWrapper object at 0x000000C5C7
C17F10>
PermissionError: [WinError 31] A device attached to the system is not functionin
g

C:\-Duino-Coin>`

Duino miner for PC 2.56... Clean install of everything, any ideas? Its happening since 2 or 3 versions ago. 

Thanks!!!

**Comment by revoxhere** [comment]
Does running the miner from source work? https://github.com/revoxhere/duino-coin#windows

**Comment by BastelPichi** [comment]
The start command looks weard, but that shouldnt change anything. This most likely means, that the arduino is already used by serial monitor or a different program. Try closing any other windows and then run again.

**Comment by IdotMaster1** [comment]
Maybe uhh, Dont use Windows Server? Its a huge waste of resources
