### ISSUE TITLE
Coloroma permission error

### ISSUE THREAD

**Issue by blin2011a** [duino-coin/duino-coin#770]
Win7 Atom x86 clean install produces following error with python3.8.10 and newest repository executed from source.

C:-Duino-Coin>pc_miner
Active code page: 65001

Traceback (most recent call last):
File "PC_Miner.py", line 1453, in 
File "PC_Miner.py", line 298, in Greeting
File "colorama\ansitowin32.py", line 41, in write
File "colorama\ansitowin32.py", line 162, in write
File "colorama\ansitowin32.py", line 187, in write_and_convert
File "colorama\ansitowin32.py", line 196, in write_plain_text
PermissionError: [WinError 31] A device attached to the system is not functionin
g

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "PC_Miner.py", line 1456, in 
File "PC_Miner.py", line 1262, in pretty_print
File "colorama\ansitowin32.py", line 41, in write
File "colorama\ansitowin32.py", line 162, in write
File "colorama\ansitowin32.py", line 187, in write_and_convert
File "colorama\ansitowin32.py", line 196, in write_plain_text
PermissionError: [WinError 31] A device attached to the system is not functionin
g
[1204] Failed to execute script PC_Miner
Traceback (most recent call last):
File "", line 1, in 
PermissionError: [WinError 31] A device attached to the system is not functionin
g
Exception ignored in: <colorama.ansitowin32.StreamWrapper object at 0x000000C5C7
C17F10>
PermissionError: [WinError 31] A device attached to the system is not functionin
g

C:-Duino-Coin>`

Ideas?

**Comment by blin2011a** [comment]
This is cpu mining on x86 not on external microcontroller.

**Comment by blin2011a** [comment]
Is there a prebuilt binary for win7 x86?

**Comment by noobflix** [comment]
Em relação a 32bit use o Ubuntu -minimal

**Comment by izonu** [comment]
the binaries are compiled for windows 10 and python is deprecated on windows 7 so update to windows 10 already or install linux

**Comment by blin2011a** [comment]
Ok gotcha, unfortunately legacy device thought give shot. No choice for upgrade. Works well on others though, cheers and thanks!

**Comment by noobflix** [comment]
> Ok, peguei, infelizmente o dispositivo legado pensou em dar uma chance. Sem escolha para atualização. Funciona bem em outros, porém, gritos e agradecimentos!

I'm Brazilian and I use 32 bit PCs I use Ubuntu minimal to mine DUINO
