### ISSUE TITLE
raspberrypi JSONDecodeError

### ISSUE THREAD

**Issue by 136ytr** [duino-coin/duino-coin#865]
pi@raspberrypi:~/duino-coin $ python3 PC_Miner.py
Traceback (most recent call last):
  File "PC_Miner.py", line 758, in <module>
    Miner.preload()
  File "PC_Miner.py", line 440, in preload
    lang_file = json.load(file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gsrbr** [comment]
Hello @136ytr , what version of the miner you are using, and whats your OS?

**Comment by oswaldzc** [comment]
> Hello @136ytr , what version of the miner you are using, and whats your OS?

hello @gsrbr ,i have same crash,using with win10 20H2, python 3.9.6 and requirement installed

**Comment by revoxhere** [comment]
Closing due to inactivity/solved in the latest versions
