### ISSUE TITLE
Miner not connecting

### ISSUE THREAD

**Issue by newuser972** [duino-coin/duino-coin#898]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f66badba220>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /getPool (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f66badba220>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PC_Miner.py", line 779, in <module>
    fastest_pool = Client.fetch_pool()
  File "PC_Miner.py", line 213, in fetch_pool
    response = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='server.duinocoin.com', port=443): Max retries exceeded with url: /getPool (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f66badba220>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by gsrbr** [comment]
Hello, are you using pc miner, yes? can u give some more informations please

1. OS
2. 32/64bit
3. miner version
4. python version 
5. U can acess this [link](https://server.duinocoin.com/getPool)?

**Comment by newuser972** [comment]
Ubuntu 21.04 64 bit PC miner 2.6.1 Python 3 and I can't access that link.  This what it says. 
This site can’t be reachedserver.duinocoin.com took too long to respond.
Try:

Checking the connection
ERR_CONNECTION_TIMED_OUT

**Comment by gsrbr** [comment]
If you can't access this [link](https://server.duinocoin.com/getPool), can be basically two things

1. Some error of ISP/Route (try to restart your router)
2. Or you've got banned(for breaking some [ToS](https://github.com/revoxhere/duino-coin#terms-of-service))

**Comment by Tech1k** [comment]
Please let me know if you managed to fix your issue with connecting to the network!

**Comment by revoxhere** [comment]
Closing due to inactivity/solved in the latest versions

**Comment by newuser972** [comment]
No everything is working well.  Thanks
