### ISSUE TITLE
It does not start any program for windows. Duino-Coin_2.7_windows version.

### ISSUE THREAD

**Issue by pinokio240** [duino-coin/duino-coin#938]
What to do to start? When launched, CMD is launched for a very short time
  and closes. Running from the Administrator does not help. Operating system WIN7x64, Python 3.8.

**Comment by Boatkungg** [comment]
Try download(clone) the repository 
1.
![3C3A2D48-DB2D-453D-99DB-9EBB49157735](https://user-images.githubusercontent.com/60977054/131385001-ce13e3a0-de73-4f54-b71f-7f9ce946c155.jpeg)

2.
![6CD5BF9B-9C79-4148-A096-EBCBC7A575FF](https://user-images.githubusercontent.com/60977054/131385019-321d7cc3-db33-4b24-a852-0879885c3977.jpeg)

and open the cmd at where you unpack the file

You can use the PC_Miner.py by type `python3 PC_Miner.py` in the cmd

You can use the AVR_Miner.py by type `python3 AVR_Miner.py` in the cmd

Hope this will help you out

**Comment by shenbushou** [comment]
when i run PC_Miner.py in pycharm 。it shows  ValueError: check_hostname requires server_hostname

**Comment by shenbushou** [comment]
Now it raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Boatkungg** [comment]
Can you try to run it in shell or cmd?

**Comment by pinokio240** [comment]
> Try download(clone) the repository
.......
> Hope this will help you out
Windows PowerShell
(C) Корпорация Майкрософт, 2009. Все права защищены.

PS C:\Users\Pluton> cd c:/Users/Pluton/Desktop/Duino-Coin_2.7_windows/duino-coin-master
PS C:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master> & "C:/Program Files/Python38/python.exe" c:/Users/Pluton/Desktop/Duino-Coin_2.7_windows/duino-coin-master/PC_Miner.py

 ‖ Официальный Duino-Coin © Python майнер (v2.7) 2019-2021
 ‖ https://github.com/revoxhere/duino-coin
 ‖ Russian translation: 5Q
 ‖ CPU: 6x AMD FX(tm)-8320 Eight-Core Processor
 ‖ Уровень пожертвования разработчикам: 0
 ‖ Алгоритм: 1 @ Сложность сети
 ‖ Идентификатор устройства: pc
 ‖ Приятного вам вечера, Pinokio240!

18:30:40  net0  Searching for the fastest node to connect to
18:30:41  net0  Retrieved mining node: beyond-pool-1
Process Process-4:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 612, in mine
    using_algo = get_string("using_algo")
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 354, in get_string
    if string_name in lang_file[lang]:
NameError: name 'lang_file' is not defined
Process Process-5:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 612, in mine
    using_algo = get_string("using_algo")
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 354, in get_string
    if string_name in lang_file[lang]:
NameError: name 'lang_file' is not defined
Process Process-6:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 612, in mine
    using_algo = get_string("using_algo")
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 354, in get_string
    if string_name in lang_file[lang]:
NameError: name 'lang_file' is not defined
Process Process-7:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 612, in mine
    using_algo = get_string("using_algo")
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 354, in get_string
    if string_name in lang_file[lang]:
NameError: name 'lang_file' is not defined
Process Process-8:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 612, in mine
    using_algo = get_string("using_algo")
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 354, in get_string
    if string_name in lang_file[lang]:
NameError: name 'lang_file' is not defined
Process Process-9:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 612, in mine
    using_algo = get_string("using_algo")
  File "c:\Users\Pluton\Desktop\Duino-Coin_2.7_windows\duino-coin-master\PC_Miner.py", line 354, in get_string
    if string_name in lang_file[lang]:
NameError: name 'lang_file' is not defined

The instructions for installing the repository for duino-coin-maste followed

**Comment by shenbushou** [comment]
> Can you try to run it in shell or cmd?

also raise it

**Comment by shenbushou** [comment]
![image](https://user-images.githubusercontent.com/64524981/131598553-0ed6f2f5-e8a5-4f12-a588-627596943af0.png)
![image](https://user-images.githubusercontent.com/64524981/131598593-31ead00a-8aa9-41a9-b66a-79833cd03fe3.png)

**Comment by shenbushou** [comment]
just dont know why

**Comment by revoxhere** [comment]
Closing due to inactivity/solved in the latest versions
