### ISSUE TITLE
The CLI_Wallet doesn't work

### ISSUE THREAD

**Issue by xbb-mcl** [duino-coin/duino-coin#956]
My CLI_Wallet doesn't work.
When the CLI_Wallet is turned on, it displays nothing (except a flashing cursor) and turns off automatically after a few seconds.
I have installed Python3
-------------------------------------
OS:Windows10 x64
Version:2.7

**Comment by zybertech07** [comment]
open cmd in your computer and drag and drop the CLI_Wallet into cmd and press enter. that will show the error message

**Comment by xbb-mcl** [comment]
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 445, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 440, in _make_request
  File "http\client.py", line 1345, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
TimeoutError: [WinError 10060]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 532, in increment
  File "urllib3\packages\six.py", line 734, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 445, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 440, in _make_request
  File "http\client.py", line 1345, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060,None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CLI_Wallet.py", line 66, in <module>
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, None, 10060, None))
[6588] Failed to execute script CLI_Wallet

**Comment by zybertech07** [comment]
did you install python 3.7+ version

**Comment by xbb-mcl** [comment]
Yes.I have installed **python-3.9.7**

**Comment by xbb-mcl** [comment]
Hello?

**Comment by gsrbr** [comment]
Hello @xbb233 for the error I believe it may be a connection error, could you try again please with the lastest version of the CLI Wallet

**Comment by revoxhere** [comment]
Closing due to inactivity/solved in the latest versions
