### ISSUE TITLE
Error on Start PC_Miner.py

### ISSUE THREAD

**Issue by Tarto97** [duino-coin/duino-coin#958]
please solution if i am start PC_Miner.py

   Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 403, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 302, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 405, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 269, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
Psutil disabled

Duino-Coin basic configuration tool
Edit Duino-Coin PC Miner 2.71/Miner_config.cfg file later if you want to change it.
Don't have an Duino-Coin account yet? Use Wallet to register on server.

Enter your Duino-Coin username:

**Comment by gsrbr** [comment]
Hello, this is an already handled exception, as seen in the message `Psutil disabled` , I believe you can mine normally, if you have some issue on the process please reporte to us.

**Comment by revoxhere** [comment]
Closing due to inactivity/solved in the latest versions
